### ISSUE TITLE
System.Aggregate Exception

### ISSUE THREAD

**Issue by MujahidRashid** [Starcounter/StarDump.Migrator.2.2#10]
During Unloading i received the following error 

System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at StarDump.Migrator22.Unload.Run() in C:\StarDumpMigrator\StarDump.Migrator.2.2-master\src\StarDump.Migrator.2.2\Unload.cs:line 131
   at StarDump.Migrator22.Handlers.<>c.<Register>b__0_0(String dumpPath) in C:\StarDumpMigrator\StarDump.Migrator.2.2-master\src\StarDump.Migrator.2.2\Handlers.cs:line 23
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-develop-daily-2309\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-develop-daily-2309\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-develop-daily-2309\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
HResult=-2146233088
---> System.OverflowException: Value was either too large or too small for an Int64.
   at System.Convert.ToInt64(UInt64 value)
   at StarDump.Common.SqlHelper.ConvertFromStarcounterToSqlite(String starcounterDataTypeName, Object value)
   at StarDump.Migrator22.SqlHelper.ConvertFromStarcounterToSqlite(String starcounterDataTypeName, Object value) in C:\StarDumpMigrator\StarDump.Migrator.2.2-master\src\StarDump.Migrator.2.2\Helpers\SqlHelper.cs:line 63
   at StarDump.Common.SqlHelper.GenerateInsertIntoValues[TColumn](List`1 columns, DumpRow row, StringBuilder sql)
   at StarDump.Common.SqlHelper.GenerateInsertIntoValues[TColumn](List`1 columns, List`1 rows, StringBuilder sql)
   at StarDump.Migrator22.Unload.<>c__DisplayClass15_0.<InsertRows>b__0() in C:\StarDumpMigrator\StarDump.Migrator.2.2-master\src\StarDump.Migrator.2.2\Unload.cs:line 210
   at System.Threading.Tasks.Task.Execute()
HResult=-2146233066

More information about this error may be available in the server error log.

**Comment by andwah** [comment]
https://github.com/Starcounter/StarDump/issues/16 similar problem that was fixed.

**Comment by MujahidRashid** [comment]
I am still getting this error after the fixed version

**Comment by andwah** [comment]
it was fixed in StarDump but not in StarDump.Migrator.2.2 i guess?

cc @ubbeK  @miyconst

**Comment by ubbeK** [comment]
@MujahidRashid Thank you for reporting. I will have to take a deeper look.

**Comment by ubbeK** [comment]
> ---> System.OverflowException: Value was either too large or too small for an Int64.
> at System.Convert.ToInt64(UInt64 value)

@MujahidRashid There is a bug in StarDump.Common when an ulong is too big for a long conversion. Will implement a solution for it.

**Comment by ubbeK** [comment]
Fix for issue has been pushed to this repository. This fix will be included in #9 release.

**Comment by miyconst** [comment]
@MujahidRashid could you please check the fix on your database before the release?

**Comment by MujahidRashid** [comment]
It works although i got the following message is this just a warning message ?

Unloaded to c:/dump/dump197.sqlite3, elapsed 03:05:58.5544804, 289 tables, 294176120 rows.
-- Messages --
 - AdFenix.Database.Campaigns.Facebook.FacebookAdAccount not found. Skipping the table. Failed to process query: SELECT i FROM "AdFenix"."Database"."Campaigns"."Facebook"."FacebookAdAccount" i: Unknown class AdFenix.Database.Campaigns.Facebook.FacebookAdAccount. 
 - AdFenix.Database.Ecommerce.ProductAd._Sold not found. Skipping the property.
 - AdFenix.Database.ClassifiedJobAd._Sold not found. Skipping the property.
 - AdFenix.Database.ClassifiedHomeAd._Sold not found. Skipping the property.
 - AdFenix.Database.ClassifiedBroadAd._Sold not found. Skipping the property.
 - AdFenix.Database.ClassifiedVehicleAd._Sold not found. Skipping the property.
 - AdFenix.Database.CompanyListingPage._Sold not found. Skipping the property.

Thanks guys for all the support

**Comment by miyconst** [comment]
@MujahidRashid thank you for the input. Yes, those are just warnings, but you should learn each of them and make sure that you no longer use those tables/properties.

If you need one of the skipped tables/properties, than you should make sure that a proper `[Database]` class is loaded.

**Comment by ubbeK** [comment]
Issue has been implemented and tested.

Closing issue
