### ISSUE TITLE
Update the application in the Warehouse

### ISSUE THREAD

**Issue by un-tone** [Starcounter/StarDump.Migrator.2.2#14]
I tried to unload DB for the `inside.starcounter.com` with the app version 0.1.1 from the Warehouse. When running the app throwed the following error.
```
System.Exception: Unable to execute SQL: INSERT INTO `Starcounter.Metadata.Column` (`Id`, `TableId`, `Name`, `DataType`, `ReferenceType`, `Nullable`, `Inherited`) VALUES ;
   at StarDump.Common.SqlHelper.ExecuteNonQuery(String sql, DbConnection cn)
   at StarDump.Migrator22.Unload.CreateTableAndInsertMetadata(SQLiteConnection cn, UnloadTable table) in C:\GitHub\Starcounter\StarDump.Migrator.2.2\src\StarDump.Migrator.2.2\Unload.cs:line 170
   at StarDump.Migrator22.Unload.<>c__DisplayClass12_0.<Run>b__1() in C:\GitHub\Starcounter\StarDump.Migrator.2.2\src\StarDump.Migrator.2.2\Unload.cs:line 57
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter\Db.cs:line 355
   at StarDump.Migrator22.Unload.<>c__DisplayClass12_0.<Run>b__0() in C:\GitHub\Starcounter\StarDump.Migrator.2.2\src\StarDump.Migrator.2.2\Unload.cs:line 51
   at Starcounter.Internal.StarcounterEnvironment.RunWithinApplication(String desiredAppName, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:line 128
   at StarDump.Migrator22.Unload.Run() in C:\GitHub\Starcounter\StarDump.Migrator.2.2\src\StarDump.Migrator.2.2\Unload.cs:line 49
   at StarDump.Migrator22.Handlers.<>c.<Register>b__0_0(String dumpPath) in C:\GitHub\Starcounter\StarDump.Migrator.2.2\src\StarDump.Migrator.2.2\Handlers.cs:line 23
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
HResult=-2146233088
---> System.Data.SQLite.SQLiteException: SQL logic error or missing database
near ";": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at StarDump.Common.SqlHelper.ExecuteNonQuery(String sql, DbConnection cn)
ErrorCode=1
HResult=-2147467259

More information about this error may be available in the server error log.
```

With the latest version which I got from the GitHub the unloading gone with no errors.

**Comment by warpech** [comment]
From what I can see, `StarDump.Migrator.2.2` is not in the Warehouse. Where did you take version 0.1.1 from then?

@miyconst it seems that version 0.1.2 is not available in GitHub Releases

**Comment by un-tone** [comment]
@warpech it was available for downloading in the Administrator. Maybe it was provided by some "old" Warehouse?

**Comment by warpech** [comment]
Hmm, that I don't know. @miyconst, @andwah pls help.

**Comment by andwah** [comment]
> Maybe it was provided by some "old" Warehouse?

it was.. i checked. Stardump v0.1.1 is ***only*** in the old warehouse it's not in the current Warehouse.

**Comment by andwah** [comment]
i will make the same version it available in the current warehouse.

**Comment by andwah** [comment]
Now user may download the StarDump.Migrator.2.2 v0.1.1 from both old and current Warehouse.

**Comment by warpech** [comment]
Can this be closed now?

**Comment by andwah** [comment]
Current version in Warehouse is 0.1.1.  is that the correct one?

**Comment by un-tone** [comment]
No, it should be 0.1.2

**Comment by andwah** [comment]
Did a new rebuild of StarDump.Migrator.2.2 with latest code, bumped the version to v0.1.3  and uploaded it to the warehouse.  it should be available now.

**Comment by warpech** [comment]
@un-tone can this be closed now?

**Comment by un-tone** [comment]
Yes, closing.
